# Generated by Django 3.0.2 on 2020-01-20 15:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.CharField(default='localhost', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='isp',
            field=models.CharField(default='default', max_length=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip',
            field=models.CharField(default='default', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
