# Generated by Django 3.0 on 2020-01-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
